name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your project needs
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code
      - name: Lint code
        run: npm run lint # Adjust this based on your linting script

      # Run tests
      - name: Run tests
        run: npm test # Replace with your test script

      # Build the project (if applicable)
      - name: Build project
        run: npm run build # Include if your project has a build step

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install --production

      # Deploy to your hosting platform (example: Heroku)
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/<your-app-name>.git
          git push heroku main
